package animalManager.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import animalManager.model.Masterinfo;
import animalManager.repository.MasterinfoRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/master") // This means URL's start with /demo (after Application path)
public class MasterinfoController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private MasterinfoRepository masterinfoRepository;

	@RequestMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewMaster (@RequestParam String animal_id, 
			@RequestParam String name, @RequestParam String gender, 
			@RequestParam int age, @RequestParam String address, 
			@RequestParam String phonenumber, @RequestParam String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Masterinfo masterinfo = new Masterinfo();
		masterinfo.setAnimalId(animal_id);
		masterinfo.setName(name);
		masterinfo.setGender(gender);
		masterinfo.setAge(age);
		masterinfo.setAddress(address);
		masterinfo.setPhonenumber(phonenumber);
		masterinfo.setEmail(email);
		masterinfoRepository.save(masterinfo);
		return "MasterSaved";
	}

	@RequestMapping(path="/all")
	public @ResponseBody Iterable<Masterinfo> getAllMasters() {
		// This returns a JSON or XML with the users
		return masterinfoRepository.findAll();
	}
	
	@RequestMapping(path="/find")
	public @ResponseBody Iterable<Masterinfo> getMaster(@RequestParam String animal_id) {
		return masterinfoRepository.findMaster(animal_id);
	}

	@RequestMapping(path="/delete")
	public @ResponseBody String deleteMaster(@RequestParam String animal_id){
		masterinfoRepository.deleteMaster(animal_id);
		return "MasterDeleted";
	}

	@RequestMapping(path="/update")
	public @ResponseBody String updateMaster(@RequestParam String animal_id, 
			@RequestParam String name, @RequestParam String gender, 
			@RequestParam int age, @RequestParam String address, 
			@RequestParam String phonenumber, @RequestParam String email){
		masterinfoRepository.updateMaster(animal_id, name, gender, age, address, phonenumber, email);
		return "MasterUpdate";
	}
}